### ISSUE TITLE
Support for OAuth2

### ISSUE THREAD

**Issue by david-poindexter** [scottksmith95/CSharp.Meetup#1]
Hi, thank you so much for this!  Do you have any plans to update for OAuth2?

**Comment by scottksmith95** [comment]
Hi, I have not maintained this in a very long time. Unfortunately I do not have the time to invest in it. If you are willing and able to make the code changes, I will gladly accept the pull request.

**Comment by david-poindexter** [comment]
Thanks @scottksmith95 - unfortunately we are spread a bit thin right now and do not have the time to invest in it either.  Hopefully someone will be able to at some point.  It would definitely be nice for use in another open source project we are hoping to launch for the DNN community.

**Comment by DanElliott** [comment]
Created a pull request.
